/**
 * Clever Compact v2.1.0 — OpenClaw Plugin
 * Publisher: Axiom Stream Group
 * https://clawhub.ai/jfulmines-star/clever-compact
 *
 * Architecture: lifecycle hooks ONLY. Does NOT register as a ContextEngine.
 * The compaction engine runs completely untouched.
 *
 * Two hooks:
 *   session:compact:before → write state file (pre-compaction save)
 *   before_prompt_build    → inject state file (post-compact / /new restore)
 */

import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from "fs";
import { join } from "path";

const MAX_STATE_AGE_HOURS = 72;
const STATE_FILE_PREFIX = "compact-state-";
const RESTORE_HEADER = "## 🔄 Clever Compact — Resuming Previous Session\n\n";

function getMemoryDir(): string {
  const workspace =
    process.env.OPENCLAW_WORKSPACE ||
    (process.env.HOME
      ? join(process.env.HOME, ".openclaw", "workspace")
      : process.cwd());
  return join(workspace, "memory");
}

function timestampedFilename(): string {
  const now = new Date();
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${STATE_FILE_PREFIX}${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}-${pad(now.getHours())}${pad(now.getMinutes())}.md`;
}

function findMostRecentStateFile(): string | null {
  const memDir = getMemoryDir();
  if (!existsSync(memDir)) return null;

  const files = readdirSync(memDir)
    .filter((f) => f.startsWith(STATE_FILE_PREFIX) && f.endsWith(".md"))
    .sort()
    .reverse();

  if (!files.length) return null;

  // Age check
  const match = files[0].match(
    /compact-state-(\d{4})-(\d{2})-(\d{2})-(\d{2})(\d{2})\.md/
  );
  if (match) {
    const [, y, mo, d, h, mi] = match;
    const fileDate = new Date(`${y}-${mo}-${d}T${h}:${mi}:00`);
    const ageHours = (Date.now() - fileDate.getTime()) / (1000 * 60 * 60);
    if (ageHours > MAX_STATE_AGE_HOURS) return null;
  }

  return join(memDir, files[0]);
}

function buildStateContent(summary?: string): string {
  const now = new Date().toISOString();
  const body =
    summary ||
    `## Active Workstreams
_(Session was idle or no summary was captured)_

## Key Decisions
_(None captured)_

## Open Tasks
_(None captured)_

## Remember Flags
_(None captured)_`;

  return `# Compact State — ${now}
_Generated by Clever Compact v2.1.0 | Axiom Stream Group_
_Read this file at the start of every session to restore context._

${body}

---
_Next session: read this file before responding to anything._
`;
}

export default function register(api: any) {
  /**
   * Hook 1: session:compact:before
   * Fires before every compaction. Writes a structured state file.
   * Does NOT touch the compaction engine — legacy compaction runs normally.
   * Available in OpenClaw ≥ 2026.3.7
   */
  api.on(
    "session:compact:before",
    async (event: { session?: { summary?: string } }) => {
      try {
        const memDir = getMemoryDir();
        if (!existsSync(memDir)) mkdirSync(memDir, { recursive: true });

        const content = buildStateContent(event?.session?.summary);
        const filepath = join(memDir, timestampedFilename());
        writeFileSync(filepath, content, "utf-8");
      } catch {
        // Non-fatal — compact proceeds normally even if write fails
      }
    }
  );

  /**
   * Hook 2: before_prompt_build
   * Fires on every turn. If a recent state file exists, prepends it to the
   * system prompt so the agent is oriented from the first message.
   * Covers: post-compact restore, /new amnesia, and cold-start continuity.
   */
  api.on("before_prompt_build", (_event: any, _ctx: any) => {
    const stateFile = findMostRecentStateFile();
    if (!stateFile) return;

    try {
      const content = readFileSync(stateFile, "utf-8");
      return {
        prependSystemContext: `${RESTORE_HEADER}${content}\n\n---\n\n`,
      };
    } catch {
      return;
    }
  });
}
