"use strict";
/**
 * Clever Compact v2.3.0 — OpenClaw Plugin
 * Publisher: Axiom Stream Group
 * https://clawhub.ai/jfulmines-star/clever-compact
 *
 * Compatible with OpenClaw 2026.4.10+
 * Uses register(api) pattern per OC plugin SDK docs.
 */

const { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } = require("fs");
const { join } = require("path");

const VERSION = "2.3.0";
const MAX_STATE_AGE_HOURS = 72;
const STATE_FILE_PREFIX = "compact-state-";
const RESTORE_HEADER = "## 🔄 Clever Compact — Resuming Previous Session\n\n";

let hasInjectedThisSession = false;

function getMemoryDir() {
  const workspace =
    process.env.OPENCLAW_WORKSPACE ||
    (process.env.HOME ? join(process.env.HOME, ".openclaw", "workspace") : process.cwd());
  const dir = join(workspace, "memory");
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  return dir;
}

function timestampedFilename() {
  const now = new Date();
  const pad = (n) => String(n).padStart(2, "0");
  return `${STATE_FILE_PREFIX}${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}-${pad(now.getHours())}${pad(now.getMinutes())}.md`;
}

function findMostRecentStateFile() {
  const memDir = getMemoryDir();
  let files;
  try {
    files = readdirSync(memDir)
      .filter((f) => f.startsWith(STATE_FILE_PREFIX) && f.endsWith(".md"))
      .sort()
      .reverse();
  } catch {
    return null;
  }
  if (!files.length) return null;

  const match = files[0].match(/compact-state-(\d{4})-(\d{2})-(\d{2})-(\d{2})(\d{2})\.md/);
  if (match) {
    const [, y, mo, d, h, mi] = match;
    const fileDate = new Date(`${y}-${mo}-${d}T${h}:${mi}:00`);
    const ageHours = (Date.now() - fileDate.getTime()) / (1000 * 60 * 60);
    if (ageHours > MAX_STATE_AGE_HOURS) return null;
  }

  return join(memDir, files[0]);
}

function writeState(summary) {
  const memDir = getMemoryDir();
  const filename = timestampedFilename();
  const filepath = join(memDir, filename);
  const now = new Date().toISOString();
  const body = summary ||
`## Active Workstreams
_(No summary provided)_

## Key Decisions
_(None captured)_

## Open Tasks
_(None captured)_

## Remember Flags
_(None captured)_`;

  const content =
`# Compact State — ${now}
_Generated by Clever Compact v${VERSION} | Axiom Stream Group_
_Pre-compaction save. Injected at session start to restore context._

> ⚠️ Do NOT include API keys, passwords, or credentials in this file.

${body}

---
_Next session: this file is injected automatically on start._
`;

  writeFileSync(filepath, content, "utf-8");
  return filepath;
}

function register(api) {
  // Expose writeState so agent can trigger it via heartbeat or manual phrase
  if (api.fn) {
    api.fn("clever-compact:write", writeState);
  }

  // Inject most recent state file once per session (session start only)
  api.on("before_prompt_build", (_event, _ctx) => {
    if (hasInjectedThisSession) return;

    const stateFile = findMostRecentStateFile();
    if (!stateFile) {
      hasInjectedThisSession = true;
      return;
    }

    try {
      const content = readFileSync(stateFile, "utf-8");
      hasInjectedThisSession = true;
      return {
        prependSystemContext: `${RESTORE_HEADER}${content}\n\n---\n\n`,
      };
    } catch {
      hasInjectedThisSession = true;
      return;
    }
  });
}

// OC 2026.4.10+ expects register as default export
module.exports = register;
module.exports.register = register;
module.exports.writeState = writeState;
