/**
 * Clever Compact v2 — OpenClaw Context Engine Plugin
 * Publisher: Axiom Stream Group
 * https://clawhub.ai/jfulmines-star/clever-compact
 *
 * Fixes three OpenClaw memory failure modes:
 *   1. /new amnesia — fresh session, agent forgets everything
 *   2. Compaction loss — compact fires mid-task, agent loses workstream
 *   3. Memory drift — old decisions quietly disappear
 *
 * How it works:
 *   - compact() fires BEFORE every compaction → writes structured state file
 *   - assemble() fires on every context build → injects most recent state file
 *   - Legacy compaction engine handles actual summarization (we just add hooks)
 */

import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "fs";
import { join } from "path";

const PLUGIN_ID = "clever-compact";
const PLUGIN_NAME = "Clever Compact";
const STATE_FILE_PREFIX = "compact-state-";
const MAX_STATE_AGE_HOURS = 72; // ignore state files older than 3 days
const STATE_INJECT_HEADER = "## 🔄 Clever Compact — Resuming Previous Session\n\n";

function getWorkspacePath(): string {
  return (
    process.env.OPENCLAW_WORKSPACE ||
    process.env.HOME ? join(process.env.HOME!, ".openclaw", "workspace") : process.cwd()
  );
}

function getMemoryDir(): string {
  return join(getWorkspacePath(), "memory");
}

function timestampedFilename(): string {
  const now = new Date();
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${STATE_FILE_PREFIX}${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}-${pad(now.getHours())}${pad(now.getMinutes())}.md`;
}

function findMostRecentStateFile(): string | null {
  const memDir = getMemoryDir();
  if (!existsSync(memDir)) return null;

  const files = readdirSync(memDir)
    .filter((f) => f.startsWith(STATE_FILE_PREFIX) && f.endsWith(".md"))
    .sort()
    .reverse();

  if (files.length === 0) return null;

  const latest = files[0];
  // Check age — parse timestamp from filename
  const match = latest.match(/compact-state-(\d{4}-\d{2}-\d{2}-\d{4})\.md/);
  if (match) {
    const [year, month, day, hhmm] = match[1].split("-");
    const hh = hhmm.slice(0, 2);
    const mm = hhmm.slice(2, 4);
    const fileDate = new Date(`${year}-${month}-${day}T${hh}:${mm}:00`);
    const ageHours = (Date.now() - fileDate.getTime()) / (1000 * 60 * 60);
    if (ageHours > MAX_STATE_AGE_HOURS) return null;
  }

  return join(memDir, latest);
}

function buildStateFile(sessionSummary: string): string {
  const now = new Date().toISOString();
  return `# Compact State — ${now}
_Generated by Clever Compact v2.0.0 | Axiom Stream Group_
_Read this file at the start of every session to restore context._

${sessionSummary}

---
_Next session: Kit reads this before responding to anything._
`;
}

function buildDefaultStateSummary(): string {
  // Fallback state template when no session summary is available
  return `## Active Workstreams
_(No workstreams were captured — session may have been idle)_

## Key Decisions
_(None captured this session)_

## Open Tasks
_(None captured this session)_

## Remember Flags
_(None captured this session)_
`;
}

export default function register(api: any) {
  api.registerContextEngine(PLUGIN_ID, () => ({
    info: {
      id: PLUGIN_ID,
      name: PLUGIN_NAME,
      ownsCompaction: false, // Let legacy engine handle actual summarization
    },

    /**
     * ingest — called when new content enters the context pipeline.
     * Pass-through: we don't modify ingestion behavior.
     */
    async ingest() {
      return { ingested: true };
    },

    /**
     * assemble — called when building the context window for a run.
     * Injects the most recent compact state file so the agent resumes
     * from where it left off, even after /new or a compaction.
     */
    async assemble({ messages }: { messages: any[] }) {
      const stateFile = findMostRecentStateFile();

      if (!stateFile) {
        return { messages, estimatedTokens: 0 };
      }

      try {
        const stateContent = readFileSync(stateFile, "utf-8");
        const injectContent = `${STATE_INJECT_HEADER}${stateContent}\n\n---\n\n`;

        // Prepend to the first user message as system context
        const enrichedMessages = [
          {
            role: "system",
            content: injectContent,
          },
          ...messages,
        ];

        const estimatedTokens = Math.ceil(injectContent.length / 4);
        return { messages: enrichedMessages, estimatedTokens };
      } catch {
        // If state file can't be read, proceed normally
        return { messages, estimatedTokens: 0 };
      }
    },

    /**
     * compact — called BEFORE every compaction.
     * This is the core of Clever Compact: write a structured state file
     * so the agent can resume after the compaction completes.
     * Returns compacted: false so the legacy engine handles actual summarization.
     */
    async compact({ session }: { session?: { summary?: string; id?: string } }) {
      const memDir = getMemoryDir();

      try {
        // Ensure memory directory exists
        if (!existsSync(memDir)) {
          mkdirSync(memDir, { recursive: true });
        }

        // Use session summary if provided, otherwise fallback template
        const summary = session?.summary || buildDefaultStateSummary();
        const stateContent = buildStateFile(summary);
        const filename = timestampedFilename();
        const filepath = join(memDir, filename);

        writeFileSync(filepath, stateContent, "utf-8");
      } catch {
        // Non-fatal — compact proceeds even if state file write fails
      }

      // Return compacted: false to let legacy engine handle summarization
      return { ok: true, compacted: false };
    },
  }));
}
